### ISSUE TITLE
System 32 bug

### ISSUE THREAD

**Issue by Manu7611** [justinl99/Crack-Minecraft-Bedrock#1]
Hello, when I copy the file into System32 it tells me that the file to replace is running so I can't change it

**Comment by jtlw99** [comment]
- Download this tool (it's very useful): https://lockhunter.com/
- After install the tool to your pc, go to system32, search for: `Windows.ApplicationModel.Store.dll`
- Right click on it, select: `What's locking this file?`
- It will open a menu. in the menu select `Unlock it!`
- After that you will be able to repace the file.

![Screenshot 2023-12-15 113403](https://github.com/jtlw99/Crack-Minecraft-Bedrock/assets/93564256/d6d2935f-aee5-4a0b-b63d-bf82383f94ee)
![Screenshot 2023-12-15 113446](https://github.com/jtlw99/Crack-Minecraft-Bedrock/assets/93564256/03287744-b95a-49ba-bb4c-0ca06d2ee984)
